export const product_list = [
	// List of all products

	{
		name: "Jour for Therapists",
		description: "Free and secure video chats for therapists.",
		url: "https://therapy.jour.com/",
		img_url: "./assets/img/jour.png",
		category: ["All", "Health", "Communication"],
		tags: ["all", "free", "web-app", "proprietary"],
	},
	{
		name: "Joplin",
		description: "An Open Source Note Taking and To-do Application.",
		url: "https://joplinapp.org/",
		img_url: "./assets/img/joplin.png",
		category: ["All", "Notes", "Productivity"],
		tags: [
			"all",
			"free",
			"opt-in",
			"open-source",
			"decentralized",
			"cross-platform",
		],
	},
	{
		name: "ChatCrypt",
		description: "Secure Web-based Group Chat.",
		url: "https://www.chatcrypt.com/",
		img_url: "./assets/img/chatcrypt.png",
		category: ["All", "Communication"],
		tags: ["all", "free", "web-app", "proprietary"],
	},
	{
		name: "Pulse",
		description: "Access to all your SMS messages, from any device.",
		url: "https://messenger.klinkerapps.com/overview/",
		img_url: "./assets/img/pulse.png",
		category: ["All", "Communication"],
		tags: ["all", "premium", "web-app", "open-source", "cross-platform"],
	},
	{
		name: "Conversations",
		description: "An open source XMPP/Jabber client for the Android platform",
		url: "https://conversations.im/",
		img_url: "./assets/img/conversations.png",
		category: ["All", "Communication"],
		tags: ["all", "premium", "open-source"],
	},
	{
		name: "CounterMail",
		description:
			"A secure and easy to use online email service, designed for maximum security and privacy.",
		url: "https://countermail.com/",
		img_url: "./assets/img/countermail.png",
		category: ["All", "Email", "Communication"],
		tags: ["all", "premium", "web-app", "proprietary"],
	},
	{
		name: "Stash",
		description:
			"A Blockchain-secured, privacy-focused personal finance manager",
		url: "https://stash.to/",
		img_url: "./assets/img/stash.svg",
		category: ["All", "Finance", "Utilities"],
		tags: ["all", "free", "web-app", "proprietary", "decentralized"],
	},
	{
		name: "RememBear",
		description: "The easiest way to remember passwords.",
		url: "https://www.remembear.com/",
		img_url: "./assets/img/remembear.svg",
		category: ["All", "Storage", "Security", "Utilities"],
		tags: ["all", "freemium", "proprietary", "cross-platform"],
	},
	{
		name: "Krypton",
		description: "Instantly sign in with easy & secure 2FA ",
		url: "https://krypt.co/",
		img_url: "./assets/img/krypton.svg",
		category: ["All", "Security", "Utilities"],
		tags: ["all", "free", "open-source", "cross-platform"],
	},
	{
		name: "Seafile",
		description: "Open source enterprise file sync and share platform.",
		url: "https://www.seafile.com/en/home/",
		img_url: "./assets/img/seafile.png",
		category: [
			"All",
			"Storage",
			"Productivity",
			"File Transfer",
			"Collaboration",
		],
		tags: ["all", "freemium", "open-source", "cross-platform"],
	},
	{
		name: "MYKI",
		description: "Offline Password Manager & 2FA Authenticator.",
		url: "https://www.myki.com/",
		img_url: "./assets/img/myki.png",
		category: ["All", "Storage", "Security", "Utilities"],
		tags: [
			"all",
			"free",
			"premium",
			"web-app",
			"proprietary",
			"cross-platform",
		],
	},
	{
		name: "Tresorit Send",
		description: "Send Big Files up to 5GB Securely.",
		url: "https://send.tresorit.com/",
		img_url: "./assets/img/tresorit-send.png",
		category: ["All", "Utilities", "File Transfer"],
		tags: ["all", "free", "web-app", "proprietary"],
	},
	{
		name: "PasswordBoss",
		description: "Secure Password Manager for Businesses and Individuals.",
		url: "https://www.passwordboss.com/",
		img_url: "./assets/img/passwordboss.png",
		category: ["All", "Storage", "Security", "Utilities"],
		tags: ["all", "web-app", "freemium", "proprietary", "cross-platform"],
	},
	{
		name: "Keyn",
		description: "Login to your accounts without Passwords.",
		url: "https://keyn.app/",
		img_url: "./assets/img/keyn.svg",
		category: ["All", "Security", "Utilities"],
		tags: ["all", "freemium", "proprietary", "cross-platform"],
	},
	{
		name: "Mailvelope",
		description:
			"An extension that provides encryption for your existing emails.",
		url: "https://www.mailvelope.com/en",
		img_url: "./assets/img/mailvelope.png",
		category: ["All", "Email", "Security", "Communication"],
		tags: ["all", "free", "open-source", "cross-platform"],
	},
	{
		name: "Day One",
		description: "A simple and cross platform journaling app.",
		url: "https://dayoneapp.com/",
		img_url: "./assets/img/dayone.png",
		category: ["All", "Notes", "Utilities"],
		tags: ["all", "freemium", "proprietary", "cross-platform"],
	},
	{
		name: "Librem One",
		description:
			"A bundle of secure, ethical and privacy-respecting products: Librem Mail, Librem Chat, Librem Files, Librem Backup, Librem Contacts.",
		url: "https://librem.one",
		img_url: "./assets/img/librem.svg",
		category: [
			"All",
			"Email",
			"Storage",
			"Productivity",
			"Communication",
			"File Transfer",
		],
		tags: [
			"all",
			"freemium",
			"open-source",
			"decentralized",
			"cross-platform",
		],
	},
	{
		name: "Status",
		description:
			"A secure P2P messenger, decentralized crypto wallet, and Web3 browser, all-in-one.",
		url: "https://status.im",
		img_url: "./assets/img/status.png",
		category: [
			"All",
			"Finance",
			"Utilities",
			"Communication",
			"File Transfer",
		],
		tags: ["all", "free", "open-source", "decentralized", "cross-platform"],
	},
	{
		name: "Criptext",
		description:
			"An encrypted email service that guarantees security, privacy and control over all your email communications.",
		url: "https://www.criptext.com/en/",
		img_url: "./assets/img/criptext.png",
		category: ["All", "Email", "Communication"],
		tags: [
			"all",
			"beta",
			"free",
			"open-source",
			"decentralized",
			"cross-platform",
		],
	},
	{
		name: "Voxer",
		description:
			"A walkie talkie messenger with end-to-end encryption when using 'Private Chats'.",
		url: "https://www.voxer.com",
		img_url: "./assets/img/voxer.png",
		category: ["All", "Communication"],
		tags: ["all", "web-app", "freemium", "proprietary", "cross-platform"],
	},
	{
		name: "FlowCrypt",
		description: "End-to-end encryption for email with PGP.",
		url: "https://www.flowcrypt.com",
		img_url: "./assets/img/flowcrypt.png",
		category: ["All", "Email", "Security", "Communication"],
		tags: ["all", "freemium", "open-source", "cross-platform"],
	},
	{
		name: "ChatSecure",
		description:
			"A free and open source messaging app for iOS with end-to-end encryption.",
		url: "https://chatsecure.org/",
		img_url: "./assets/img/chatsecure.png",
		category: ["All", "Communication"],
		tags: ["all", "free", "open-source"],
	},
	{
		name: "Symphony",
		description:
			"Secure team communication, file-sharing and automation tools for financial firms.",
		url: "https://symphony.com/",
		img_url: "./assets/img/symphony.png",
		category: ["All", "Communication", "File Transfer", "Collaboration"],
		tags: ["all", "premium", "proprietary", "cross-platform"],
	},
	{
		name: "ToffeeShare",
		description:
			"Private & secure peer-to-peer file transfer, with no size limits.",
		url: "https://toffeeshare.com/",
		img_url: "./assets/img/toffeeshare.png",
		category: ["All", "File Transfer"],
		tags: ["all", "web-app", "freemium", "proprietary"],
	},
	{
		name: "wölkli Mail",
		description: "Swiss email built with privacy and security in mind.",
		url: "https://woelklimail.com/en",
		img_url: "./assets/img/woelklimail.png",
		category: ["All", "Email", "Communication"],
		tags: ["all", "web-app", "freemium", "proprietary"],
	},
	{
		name: "Confrere",
		description: "1-on-1 Video calling for professionals.",
		url: "https://confrere.com/",
		img_url: "./assets/img/confrere.png",
		category: ["All", "Communication"],
		tags: ["all", "premium", "web-app", "proprietary"],
	},
	{
		name: "Webex Teams",
		description: "Secure team collaboration, file sharing and messaging.",
		url: "https://www.webex.com/team-collaboration.html",
		img_url: "./assets/img/webexteams.png",
		category: ["All", "Communication", "File Transfer", "Collaboration"],
		tags: ["all", "web-app", "freemium", "proprietary", "cross-platform"],
	},
	{
		name: "NextCloud",
		description:
			"A self-hosted productivity platform & suite of products for individuals and teams.",
		url: "https://nextcloud.com/",
		img_url: "./assets/img/nextcloud.png",
		category: [
			"All",
			"Email",
			"Storage",
			"Productivity",
			"Communication",
			"File Transfer",
			"Collaboration",
		],
		tags: ["all", "free", "premium", "open-source", "cross-platform"],
	},
	{
		name: "Cyph",
		description: "Easy quantum-computing-resistant messaging on any device.",
		url: "https://cyph.com/",
		img_url: "./assets/img/cyph.png",
		category: ["All", "Notes", "Storage", "Communication"],
		tags: ["all", "web-app", "freemium", "open-source", "cross-platform"],
	},
	{
		name: "Jetdrop",
		description: "Free & secure file sharing upto 10GB.",
		url: "https://www.jetdrop.net/",
		img_url: "./assets/img/jetdrop.png",
		category: ["All", "File Transfer"],
		tags: ["all", "free", "web-app", "proprietary"],
	},
	{
		name: "Zebu",
		description:
			"Messaging, file management and scheduling all in one platform ",
		url: "https://www.zebu.io",
		img_url: "./assets/img/zebu.svg",
		category: ["All", "Storage", "Productivity", "Communication"],
		tags: ["all", "web-app", "freemium", "proprietary", "cross-platform"],
	},
	{
		name: "Kontalk",
		description:
			"Community-driven, encrypted, distributed and open-source instant messaging.",
		url: "https://www.kontalk.org/",
		img_url: "./assets/img/kontalk.png",
		category: ["All", "Communication", "File Transfer"],
		tags: ["all", "free", "open-source", "cross-platform"],
	},
	{
		name: "Silence",
		description:
			"A full replacement for the default text messaging application where all messages are encrypted.",
		url: "https://www.silence.im",
		img_url: "./assets/img/silence.png",
		category: ["All", "Communication"],
		tags: ["all", "free", "open-source"],
	},
	{
		name: "Rocket.Chat",
		description:
			"A scalable & open source communication and collaboration tool for teams.",
		url: "https://www.rocket.chat",
		img_url: "./assets/img/rocketchat.png",
		category: [
			"All",
			"Utilities",
			"Productivity",
			"Communication",
			"Collaboration",
		],
		tags: [
			"all",
			"free",
			"web-app",
			"freemium",
			"open-source",
			"cross-platform",
		],
	},
	{
		name: "FortKnoxster",
		description: "Private and secure messaging, calling and storage.",
		url: "https://www.fortknoxster.com",
		img_url: "./assets/img/fortknoxster.png",
		category: [
			"All",
			"Storage",
			"Communication",
			"File Transfer",
			"Collaboration",
		],
		tags: [
			"all",
			"free",
			"web-app",
			"proprietary",
			"decentralized",
			"cross-platform",
		],
	},
	{
		name: "Jami",
		description:
			"Distributed communication platform which respects the freedom and privacy of users.",
		url: "https://www.jami.net",
		img_url: "./assets/img/jami.png",
		category: ["All", "Communication", "Collaboration"],
		tags: ["all", "free", "open-source", "cross-platform"],
	},
	{
		name: "Seecrypt",
		description:
			"Secure real-time messaging, voice, and conference calls & encrypted file sharing.",
		url: "https://www.seecrypt.com/",
		img_url: "./assets/img/seecrypt.png",
		category: ["All", "Communication", "File Transfer"],
		tags: ["all", "premium", "proprietary", "cross-platform"],
	},
	{
		name: "PreVeil",
		description:
			"Encrypted email and file sharing for individuals and businesses.",
		url: "https://www.preveil.com",
		img_url: "./assets/img/preveil.png",
		category: ["All", "Email", "Storage", "Communication", "File Transfer"],
		tags: ["all", "web-app", "freemium", "proprietary", "cross-platform"],
	},
	{
		name: "Sync",
		description:
			"Secure cloud storage & file transfer with end-to-end encryption",
		url: "https://www.sync.com",
		img_url: "./assets/img/sync.png",
		category: ["All", "Storage", "File Transfer"],
		tags: ["all", "web-app", "freemium", "proprietary", "cross-platform"],
	},
	{
		name: "Tok",
		description: "Distributed, Anonymous & Secure Messaging",
		url: "https://www.tok.life",
		img_url: "./assets/img/tok.png",
		category: ["All", "Communication"],
		tags: ["all", "free", "open-source", "decentralized", "cross-platform"],
	},
	{
		name: "Session",
		description:
			"An end-to-end encrypted messenger that removes sensitive metadata collection.",
		url: "https://getsession.org/",
		img_url: "./assets/img/session.png",
		category: ["All", "Communication", "File Transfer"],
		tags: ["all", "free", "open-source", "decentralized", "cross-platform"],
	},
	{
		name: "Inkdrop",
		description:
			"End-to-end encrypted note-taking app with robust Markdown editor built for devs.",
		url: "https://inkdrop.app/",
		img_url: "./assets/img/inkdrop.png",
		category: ["All", "Notes", "Productivity"],
		tags: ["all", "premium", "web-app", "proprietary", "cross-platform"],
	},
	{
		name: "ownCloud",
		description:
			"Open-source, self-hosted and secure file sync, share and storage for individuals & businesses.",
		url: "https://owncloud.com/",
		img_url: "./assets/img/owncloud.svg",
		category: [
			"All",
			"Storage",
			"Productivity",
			"File Transfer",
			"Collaboration",
		],
		tags: ["all", "freemium", "open-source", "cross-platform"],
	},
	{
		name: "Pushbullet",
		description:
			"Share links, messages, files and notifications across your connected devices. ",
		url: "https://www.pushbullet.com/",
		img_url: "./assets/img/pushbullet.png",
		category: ["All", "Utilities", "Productivity", "File Transfer"],
		tags: ["all", "web-app", "freemium", "proprietary", "cross-platform"],
	},
	{
		name: "FocusWriter",
		description:
			"A free, private, distraction-free and customizable writing app.",
		url: "https://focuswriter.co/",
		img_url: "./assets/img/focuswriter.png",
		category: ["All", "Notes", "Productivity"],
		tags: ["all", "free", "web-app", "proprietary", "decentralized"],
	},
	{
		name: "Okuna",
		description:
			" Crowd-funded, open-source, ethical social network for a brighter tomorrow. ",
		url: "https://www.okuna.io/",
		img_url: "./assets/img/okuna.png",
		category: ["All", "Utilities", "Communication"],
		tags: ["all", "beta", "free", "web-app", "open-source"],
	},
	{
		name: "Passwork",
		description: "Cloud and Self-hosted password manager for businesses.",
		url: "https://passwork.me/",
		img_url: "./assets/img/passwork.png",
		category: ["All", "Storage", "Security", "Utilities"],
		tags: ["all", "premium", "web-app", "proprietary", "cross-platform"],
	},
	{
		name: "Firefox Send",
		description:
			"Share files with end-to-end encryption and a link that automatically expires.",
		url: "https://send.firefox.com",
		img_url: "./assets/img/firefoxsend.svg",
		category: ["All", "File Transfer"],
		tags: ["all", "free", "web-app", "open-source"],
	},
	{
		name: "Datash",
		description: "Send and receive files with end-to-end encryption.",
		url: "https://datash.co/",
		img_url: "./assets/img/datash.png",
		category: ["All", "File Transfer"],
		tags: ["all", "free", "web-app", "open-source"],
	},
	{
		name: "EteSync",
		description:
			"Secure, end-to-end encrypted, and privacy respecting sync for your contacts, calendars and tasks.",
		url: "https://www.etesync.com/",
		img_url: "./assets/img/etesync.png",
		category: ["All", "Productivity"],
		tags: ["all", "web-app", "premium", "open-source", "cross-platform"],
	},
	{
		name: "Scannie",
		description:
			"Secure and end-to-end encrypted document scanner and storage.",
		url: "https://www.scannieapp.com/",
		img_url: "./assets/img/scannie.png",
		category: ["All", "Productivity"],
		tags: ["all", "free", "open-source", "decentralized"],
	},
	{
		name: "Wickr",
		description:
			"Fully encrypted, Enterprise-ready, Private, Secure Team Collaboration Space",
		url: "https://wickr.com/",
		img_url: "./assets/img/wickr.png",
		category: ["All", "Communication", "Collaboration"],
		tags: ["all", "freemium", "proprietary", "cross-platform"],
	},
	{
		name: "Wire",
		description:
			"A collaboration platform with the most advanced security and superior user experience.",
		url: "https://wire.com/en/",
		img_url: "./assets/img/wire.png",
		category: [
			"All",
			"Productivity",
			"Communication",
			"File Transfer",
			"Collaboration",
		],
		tags: ["all", "web-app", "freemium", "open-source", "cross-platform"],
	},
	{
		name: "Tox",
		description:
			"Encrypted instant messaging that is free, distributed, and open-source.",
		url: "https://tox.chat/",
		img_url: "./assets/img/tox.svg",
		category: ["All", "Communication", "File Transfer", "Collaboration"],
		tags: ["all", "beta", "free", "open-source", "cross-platform"],
	},
	{
		name: "Riot",
		description:
			"A secure and robust communication and collaboration platform.",
		url: "https://about.riot.im/",
		img_url: "./assets/img/riot.svg",
		category: ["All", "Communication", "File Transfer", "Collaboration"],
		tags: [
			"all",
			"free",
			"web-app",
			"open-source",
			"decentralized",
			"cross-platform",
		],
	},
	{
		name: "Mumble",
		description:
			"An end to end encrypted text and voice chat for online communities.",
		url: "https://trymumble.com",
		img_url: "./assets/img/mumble.svg",
		category: ["All", "Communication", "Collaboration"],
		tags: ["all", "free", "web-app", "proprietary", "decentralized"],
	},
	{
		name: "MsgSafe.io",
		description:
			"Ephemeral Chat, Encrypted Voice and Video Calling, and End-to-End Encrypted Email.",
		url: "https://www.msgsafe.io",
		img_url: "./assets/img/msgsafe.png",
		category: [
			"All",
			"Email",
			"Productivity",
			"Communication",
			"File Transfer",
		],
		tags: [
			"all",
			"beta",
			"web-app",
			"freemium",
			"proprietary",
			"cross-platform",
		],
	},
	{
		name: "Viber",
		description:
			"Free and secure calls and messages with end-to-end encryption.",
		url: "https://www.viber.com/",
		img_url: "./assets/img/viber.svg",
		category: ["All", "Communication"],
		tags: ["all", "free", "proprietary", "cross-platform"],
	},
	{
		name: "Facebook Messenger",
		description:
			"End-to-end encrypted messages when using opt-in 'Secret Conversations'.",
		url: "https://www.messenger.com/",
		img_url: "./assets/img/messenger.svg",
		category: ["All", "Communication", "File Transfer"],
		tags: [
			"all",
			"free",
			"opt-in",
			"web-app",
			"proprietary",
			"cross-platform",
		],
	},
	{
		name: "Stackfield",
		description: "Encrypted projects, tasks & team communication.",
		url: "https://www.stackfield.com/",
		img_url: "./assets/img/stackfield.png",
		category: ["All", "Productivity", "Communication", "Collaboration"],
		tags: ["all", "web-app", "freemium", "proprietary", "cross-platform"],
	},
	{
		name: "dPhone",
		description:
			"A secure calling app with P2P architecture and end-to-end encryption.",
		url: "https://dphone.app/",
		img_url: "./assets/img/dphone.png",
		category: ["All", "Communication"],
		tags: ["all", "free", "open-source", "decentralized"],
	},
	{
		name: "Signal",
		description: "Fast, simple, and secure messaging",
		url: "https://signal.org/",
		img_url: "./assets/img/signal.png",
		category: ["All", "Communication"],
		tags: ["all", "free", "open-source", "cross-platform"],
	},
	{
		name: "Keybase Chat",
		description: "End-to-end encrypted chat built into Keybase",
		url: "https://keybase.io/download",
		img_url: "./assets/img/keybase.png",
		category: ["All", "Storage", "Communication", "File Transfer"],
		tags: ["all", "free", "open-source", "cross-platform"],
	},
	{
		name: "Safer.Chat",
		description:
			"End-to-end encrypted group webchat that allows users to create rooms with up to 4 participants.",
		url: "https://safer.chat/",
		img_url: "./assets/img/saferchat.png",
		category: ["All", "Communication"],
		tags: ["all", "free", "web-app", "open-source"],
	},
	{
		name: "Confide",
		description:
			"Confidential messenger with encrypted, ephemeral and screenshot-proof messages.",
		url: "https://getconfide.com/",
		img_url: "./assets/img/confide.png",
		category: ["All", "Communication"],
		tags: ["all", "freemium", "proprietary", "cross-platform"],
	},
	{
		name: "Skype",
		description:
			"End-to-end encryption when using Private Conversations (opt-in and not on by default)",
		url: "https://skype.com/en",
		img_url: "./assets/img/skype.svg",
		category: ["All", "Communication"],
		tags: [
			"all",
			"free",
			"opt-in",
			"web-app",
			"proprietary",
			"cross-platform",
		],
	},
	{
		name: "Google Duo",
		description: "Simple and secure video calling with upto 8 people.",
		url: "https://duo.google.com/about/",
		img_url: "./assets/img/duo.png",
		category: ["All", "Communication"],
		tags: ["all", "free", "web-app", "proprietary", "cross-platform"],
	},
	{
		name: "Telegram",
		description:
			"A cloud-based messaging app which offers e2ee when using Secret Chats",
		url: "https://telegram.org/",
		img_url: "./assets/img/telegram.png",
		category: ["All", "Communication"],
		tags: [
			"all",
			"free",
			"opt-in",
			"web-app",
			"proprietary",
			"cross-platform",
		],
	},
	{
		name: "WhatsApp",
		description:
			"A Facebook-owned calling and messaging app with end-to-end encryption.",
		url: "https://www.whatsapp.com/",
		img_url: "./assets/img/whatsapp.svg",
		category: ["All", "Communication"],
		tags: ["all", "free", "proprietary", "cross-platform"],
	},
	{
		name: "KeeperChat",
		description:
			"Communicate privately with end-to-end encryption for messages at rest and in transit.",
		url: "https://keepersecurity.com/keeperchat.html",
		img_url: "./assets/img/keeperchat.png",
		category: ["All", "Communication"],
		tags: ["all", "premium", "proprietary", "cross-platform"],
	},
	{
		name: "Threema",
		description:
			"An encrypted messenger built with security and privacy in mind.",
		url: "https://threema.ch/en",
		img_url: "./assets/img/threema.svg",
		category: ["All", "Communication"],
		tags: ["all", "premium", "proprietary", "cross-platform"],
	},
	{
		name: "Tutanota Mail",
		description:
			"A secure email service with built-in encrypted calendar & contacts, easy to use and private by design.",
		url: "https://tutanota.com/secure-email",
		img_url: "./assets/img/tutanota.svg",
		category: ["All", "Email", "Utilities", "Communication", "Productivity"],
		tags: ["all", "web-app", "freemium", "open-source", "cross-platform"],
	},
	{
		name: "ProtonMail",
		description:
			"An encrypted email service with modern design, integrated encrypted calendar and contacts.",
		url: "https://protonmail.com/",
		img_url: "./assets/img/protonmail.svg",
		category: ["All", "Email", "Communication"],
		tags: ["all", "web-app", "freemium", "open-source", "cross-platform"],
	},
	{
		name: "Mailfence",
		description:
			"End-to-end encrypted emails, contacts, calendars and documents.",
		url: "https://mailfence.com/",
		img_url: "./assets/img/mailfence.png",
		category: ["All", "Email", "Communication"],
		tags: ["all", "web-app", "freemium", "proprietary"],
	},
	{
		name: "Canary Mail",
		description:
			"An email <b>client</b> with built-in end-to-end encryption.",
		url: "https://canarymail.io/",
		img_url: "./assets/img/canarymail.png",
		category: ["All", "Email"],
		tags: ["all", "premium", "proprietary"],
	},
	{
		name: "Mega",
		description:
			"A simple, convenient & secure cloud storage and communication.",
		url: "https://mega.nz/",
		img_url: "./assets/img/mega.svg",
		category: ["All", "Storage", "Communication", "File Transfer"],
		tags: ["all", "web-app", "freemium", "open-source", "cross-platform"],
	},
	{
		name: "Tresorit",
		description:
			"End-to-end encrypted secure cloud to store, sync and share files easily from anywhere, anytime.",
		url: "https://tresorit.com/",
		img_url: "./assets/img/tresorit.svg",
		category: ["All", "Storage", "Productivity"],
		tags: ["all", "web-app", "premium", "proprietary", "cross-platform"],
	},
	{
		name: "pDrive",
		description:
			"A safe, secure and 100% private storage with built-in end-to-end encryption.",
		url: "https://pdrive.co/",
		img_url: "./assets/img/pdrive.png",
		category: ["All", "Storage"],
		tags: ["all", "free", "web-app", "proprietary", "decentralized"],
	},
	{
		name: "Encrypt My Photos",
		description: "End-to-end encrypted photo storage 📸",
		url: "https://encryptmyphotos.com/",
		img_url: "./assets/img/encryptmyphotos.png",
		category: ["All", "Storage"],
		tags: ["all", "free", "web-app", "open-source", "decentralized"],
	},
	{
		name: "Photo Vault",
		description:
			"Unlimited free and secure storage for your private photos with end-to-end encryption.",
		url: "https://photovault.online/",
		img_url: "./assets/img/photovault.png",
		category: ["All", "Storage"],
		tags: ["all", "free", "web-app", "proprietary", "decentralized"],
	},
	{
		name: "Recall Photos",
		description:
			"A secure, free, end-to-end encrypted and open-source alternative to Google Photos.",
		url: "https://app.recall.photos/",
		img_url: "./assets/img/recallphotos.svg",
		category: ["All", "Storage"],
		tags: ["all", "free", "web-app", "open-source", "decentralized"],
	},
	{
		name: "Pixus",
		description: "Organize, explore and share end-to-end encrypted photos.",
		url: "https://pixus.tech/",
		img_url: "./assets/img/pixus.png",
		category: ["All", "Storage"],
		tags: ["all", "free", "web-app", "open-source", "decentralized"],
	},
	{
		name: "Boxcryptor",
		description: "End-to-end encryption for your cloud data.",
		url: "https://www.boxcryptor.com/en/",
		img_url: "./assets/img/boxcryptor.png",
		category: ["All", "Security", "Utilities", "Storage"],
		tags: ["all", "freemium", "proprietary", "cross-platform"],
	},
	{
		name: "NordLocker",
		description: "File encryption: store and share data securely",
		url: "https://nordlocker.com/",
		img_url: "./assets/img/nordlocker.png",
		category: ["All", "Storage", "Productivity", "File Transfer"],
		tags: ["all", "premium", "proprietary", "cross-platform"],
	},
	{
		name: "Virtru",
		description:
			"Easily Protect Your Data Wherever It’s Created or Shared with End-to-End Encryption.",
		url: "https://www.virtru.com/",
		img_url: "./assets/img/virtru.png",
		category: [
			"All",
			"Email",
			"Storage",
			"Security",
			"Communication",
			"File Transfer",
		],
		tags: ["all", "premium", "cross-platform"],
	},
	{
		name: "Bitwarden",
		description:
			"Open source password management solutions with end-to-end encryption.",
		url: "https://www.bitwarden.com/",
		img_url: "./assets/img/bitwarden.png",
		category: ["All", "Storage", "Utilities", "Security", "Productivity"],
		tags: ["all", "web-app", "freemium", "open-source", "cross-platform"],
	},
	{
		name: "Padloc",
		description:
			"A modern, open-source and encrypted password manager for individuals and teams.",
		url: "https://padloc.app/",
		img_url: "./assets/img/padloc.png",
		category: ["All", "Storage", "Utilities", "Security", "Productivity"],
		tags: [
			"all",
			"beta",
			"web-app",
			"freemium",
			"open-source",
			"cross-platform",
		],
	},
	{
		name: "LastPass",
		description:
			"Password manager and digital vault to manage your credentials.",
		url: "https://www.lastpass.com/",
		img_url: "./assets/img/lastpass.svg",
		category: ["All", "Storage", "Utilities", "Security", "Productivity"],
		tags: ["all", "web-app", "freemium", "proprietary", "cross-platform"],
	},
	{
		name: "Roboform",
		description: "Password management tool for individuals and businesses.",
		url: "https://www.roboform.com/",
		img_url: "./assets/img/roboform.png",
		category: ["All", "Storage", "Utilities", "Security", "Productivity"],
		tags: ["all", "web-app", "freemium", "proprietary", "cross-platform"],
	},
	{
		name: "1Password",
		description: "A private by design end-to-end encrypted password manager.",
		url: "https://www.1password.com/",
		img_url: "./assets/img/1password.png",
		category: ["All", "Storage", "Utilities", "Security", "Productivity"],
		tags: ["all", "premium", "web-app", "proprietary", "cross-platform"],
	},
	{
		name: "Standard Notes",
		description: "A free, open-source, and completely encrypted notes app.",
		url: "https://standardnotes.org",
		img_url: "./assets/img/snotes.svg",
		category: ["All", "Notes", "Productivity"],
		tags: ["all", "web-app", "freemium", "open-source", "cross-platform"],
	},
	{
		name: "Notes by Firefox",
		description:
			"A simple, secure notepad extension for Firefox that has a companion app for Android. ",
		url: "https://addons.mozilla.org/en-US/firefox/addon/notes-by-firefox/",
		img_url: "./assets/img/firefoxnotes.png",
		category: ["All", "Notes", "Productivity"],
		tags: ["all", "beta", "free", "open-source"],
	},
	{
		name: "Recap",
		description:
			"UK crypto Capital Gains tax reports & filing with end-to-end encryption.",
		url: "https://recap.io/",
		img_url: "./assets/img/recap.png",
		category: ["All", "Finance", "Productivity"],
		tags: ["all", "web-app", "freemium", "proprietary"],
	},
];

// List of available tags
export const tag_list = [
	"all",
	"beta",
	"free",
	"opt-in",
	"web-app",
	"premium",
	"freemium",
	"proprietary",
	"open-source",
	"decentralized",
	"cross-platform", //, "", "", "", "", ""
];
// List of available categories
export const catergory_list = [
	"All",
	"Email",
	"Notes",
	"Health",
	"Storage",
	"Finance",
	"Security",
	"Utilities",
	"Productivity",
	"File Transfer",
	"Collaboration",
	"Communication",
];
